---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.11.2-ce.0 # last version at 2025-05-10
    container_name: gitlab
    hostname: gitlab
    ports:
      - 9000:80      # Web UI
      - 52525:22     # SSH (for cloning via SSH)
    volumes:
      - ./config:/etc/gitlab           # GitLab configuration
      - ./logs:/var/log/gitlab         # Logs
      - ./data:/var/opt/gitlab         # GitLab data (repositories, CI pipelines, etc)
    shm_size: '256m'                   # Shared memory size (GitLab recommends increasing this)
    networks:
      - gitnet
    restart: always

  gitlab-runner:
    image: gitlab/gitlab-runner:v17.11.1 # last version at 2025-05-10
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Enables docker commands inside runner (if needed)
      - ./gitlab-runner/config:/etc/gitlab-runner # Stores runner registration/config
    env_file:
      - .env
    entrypoint: ["/bin/bash", "-c", "
        apt-get update && apt-get install -y make curl rsync;
        curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh;
        if [ ! -f /etc/gitlab-runner/config.toml ]; then
          gitlab-runner register \
            --non-interactive \
            --url \"$CI_SERVER_URL\" \
            --registration-token \"$CI_REGISTRATION_TOKEN\" \
            --executor shell \
            --description \"Shell Runner\";
        fi;
        exec gitlab-runner run
    "]
    networks:
      - gitnet
    restart: always

    # WARNING:
    # This runner uses the 'shell' executor, which executes CI jobs directly inside the container.
    # This is NOT secure in production or shared environments.
    # TODO: Migrate to Docker executor with isolated containers for better security.

networks:
  gitnet:
    name: gitnet
    external: true # You must create this network manually using: docker network create gitnet
